apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: DMSSBOpenShift
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: DMSSBOpenShift
    spec:
      containers:
      - name: DMSSBOpenShift
        image: openshift/DMSSBOpenShift:latest
        ports:
        - containerPort: 8080
          env:
          - name: JAVA_APP_JAR
            value: ${project.artifactId}-${project.version}.war